// <auto-generated />
namespace Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ImageNullableuploadedByUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageNullableuploadedByUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201306251029399_ImageNullableuploadedByUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
