// <auto-generated />
namespace Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSubmittedDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSubmittedDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201306300929490_AddSubmittedDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
