// <auto-generated />
namespace Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_FileData_Image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_FileData_Image));
        
        string IMigrationMetadata.Id
        {
            get { return "201306250921168_Added_FileData_Image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
